FROM node:18

ENV DOCKERIZE_VERSION v0.7.0

RUN apt-get update \
    && apt-get install -y wget \
    && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
    && apt-get autoremove -yqq --purge wget && rm -rf /var/lib/apt/lists/*

# setar um usuário resolve problemas de vulnerabilidade
# usar o usuário que tenha o mesmo id do usuário local 
USER node

WORKDIR /usr/src/app

EXPOSE 3000
